---
- name: Install ssh client
  apt:
    state: present
    name: "{{ item }}"
  with_items:
    - openssh-client
  when: openssh_client
  tags:
    - install
    - openssh

- name: Install ssh server
  apt:
    state: present
    name: "{{ item }}"
  with_items:
    - openssh-server
  when: openssh_server
  tags:
    - install
    - openssh
