---
- name: Install ssh client
  package:
    state: present
    name: "{{ openssh_client_pkg_name }}"
  when: openssh_client
  tags:
    - install
    - openssh

- name: Install ssh server
  package:
    state: present
    name: "{{ openssh_server_pkg_name }}"
  when: openssh_server
  tags:
    - install
    - openssh
