---
- include: intuitive-naming.yml

- name: service | ssh | started
  service:
    name: "{{ openssh_service_name }}"
    state: started
  when:
    - ansible_connection != "chroot"

- name: service | ssh | stopped
  service:
    name: "{{ openssh_service_name }}"
    state: stopped
  when:
    - ansible_connection != "chroot"

- name: service | ssh | restarted
  service:
    name: "{{ openssh_service_name }}"
    state: restarted
  when:
    - ansible_connection != "chroot"

- name: service | ssh | reloaded
  service:
    name: "{{ openssh_service_name }}"
    state: reloaded
  when:
    - ansible_connection != "chroot"
