---
- include: intuitive-naming.yml

- name: service | ssh | started
  service:
    name: "{{ openssh_service_name }}"
    state: started

- name: service | ssh | stopped
  service:
    name: "{{ openssh_service_name }}"
    state: stopped

- name: service | ssh | restarted
  service:
    name: "{{ openssh_service_name }}"
    state: restarted

- name: service | ssh | reloaded
  service:
    name: "{{ openssh_service_name }}"
    state: reloaded
